# PATH
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.rbenv/bin"
export PATH="$PATH:$HOME/.ebcli-virtual-env/executables"
export PATH="$PATH:$HOME/protoc3/bin"
export PATH="$PATH:$HOME/Android/Sdk/platform-tools"
export PATH="$PATH/usr/local/go/bin"
export PATH="$PATH:$(go env GOPATH)/bin"
export PATH="$PATH:$HOME/.npm-global/bin"
export PATH="$PATH:/usr/local/texlive/2019/bin/x86_64-linux"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/opt/td-agent/embedded/bin"
export PATH="$PATH:/snap/bin"
export PATH="$PATH:$HOME/.anyenv/bin"

